title: dev.drawyourmind
author: mooooburg-dev
email: jeongmupark@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: https://mooooburg-dev.github.io
url: https://mooooburg-dev.github.io

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: κ°λ°λ…ΈνΈ
  tagline: dev.note
  date_format: '%b %-d, %Y'
  style: black
  showNav: true
  showPicker: true
  disqus_shortname: mooooburg-dev-github-io
  analytics_id: G-F7SQ155WCF

  # generate social links in footer
  social_links:
    twitter: jeongmu
    github: mooooburg-dev
    linkedIn: in/jeongmu-park-7b064b27
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# Build settings
# theme: texture

asset_url: /assets
plugins:
  - jekyll-seo-tag
#  - jekyll-feed
