title: dev.note
author: mooooburg-dev
email: jeongmupark@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm a Frontend Developer. Using Javascript, React, Next.js with Typescript. Backend side, Node.js, Spring. Here is my tech blog web page.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ''
url: 'https://dev.drawyourmind.com'

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: κ°λ°λ…ΈνΈ
  tagline: dev.note
  date_format: '%b %-d, %Y'
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: mooooburg-dev-github-io
  analytics_id: G-WW18CJXG1T

  # generate social links in footer
  social_links:
    twitter: jeongmu
    github: mooooburg-dev
    linkedIn: in/jeongmupark
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

paginate: 10

# Build settings
# theme: texture

asset_url: /assets
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-feed
